# Generated by Django 4.0.2 on 2022-02-18 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Super_Type', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supertype',
            name='name',
        ),
        migrations.RemoveField(
            model_name='supertype',
            name='power',
        ),
        migrations.AddField(
            model_name='supertype',
            name='type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
