# Generated by Django 4.0.2 on 2022-02-18 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Super_Type', '0002_remove_supertype_name_remove_supertype_power_and_more'),
        ('supers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HeroesVillains',
            new_name='Supers',
        ),
    ]
